const places = [
  {
    name: "مصر الجديدة",
    name_en: "Heliopolis",
    latitude: 30.0827,
    المحافظة: "القاهرة",
    longitude: 31.2947,
  },
  {
    name: "مدينة نصر",
    name_en: "Nasr City",
    latitude: 30.0511,
    المحافظة: "القاهرة",
    longitude: 31.3656,
  },
  {
    name: "المعادي",
    name_en: "Maadi",
    latitude: 29.9602,
    المحافظة: "القاهرة",
    longitude: 31.2497,
  },
  {
    name: "وسط البلد",
    name_en: "Downtown Cairo",
    latitude: 30.0444,
    المحافظة: "القاهرة",
    longitude: 31.2357,
  },
  {
    name: "شبرا",
    name_en: "Shubra",
    latitude: 30.0667,
    المحافظة: "القاهرة",
    longitude: 31.2458,
  },
  {
    name: "عين شمس",
    name_en: "Ain Shams",
    latitude: 30.1308,
    المحافظة: "القاهرة",
    longitude: 31.3139,
  },
  {
    name: "المطرية",
    name_en: "El Matareya",
    latitude: 30.1147,
    المحافظة: "القاهرة",
    longitude: 31.3136,
  },
  {
    name: "حدائق القبة",
    name_en: "Hadayek El Kobba",
    latitude: 30.0869,
    المحافظة: "القاهرة",
    longitude: 31.2783,
  },
  {
    name: "الزيتون",
    name_en: "El Zaytoun",
    latitude: 30.1167,
    المحافظة: "القاهرة",
    longitude: 31.3167,
  },
  {
    name: "الزمالك",
    name_en: "Zamalek",
    latitude: 30.0597,
    المحافظة: "القاهرة",
    longitude: 31.2236,
  },
  {
    name: "السيدة زينب",
    name_en: "El Sayeda Zeinab",
    latitude: 30.0292,
    المحافظة: "القاهرة",
    longitude: 31.2422,
  },
  {
    name: "البساتين",
    name_en: "El Basatin",
    latitude: 29.9747,
    المحافظة: "القاهرة",
    longitude: 31.2847,
  },
  {
    name: "دار السلام",
    name_en: "Dar El Salam",
    latitude: 29.9917,
    المحافظة: "القاهرة",
    longitude: 31.2417,
  },
  {
    name: "المقطم",
    name_en: "Mokattam",
    latitude: 30.0208,
    المحافظة: "القاهرة",
    longitude: 31.3281,
  },
  {
    name: "روض الفرج",
    name_en: "Rod El Farag",
    latitude: 30.0833,
    المحافظة: "القاهرة",
    longitude: 31.2333,
  },
  {
    المحافظة: " القاهرة",
    المركز: "قسم التبين",
    latitude: "29.8000",
    longitude: "31.3000",
  },
];

export default places;
